testlink.url=http://pdsiplan/testlink/lib/api/xmlrpc.php
testlink.devkey=20998a8b614dfd56bf30e2650931ee4a
testlink.projeto=Projeto Teste

jira.uri=http://jeap.rio.rj.gov.br/jira
jira.user=26226899
jira.pass=
jira.chave=TEJAVA

proxy=proxy.rio.rj.gov.br:8080