selenium.browser = chrome
selenium.iedriver = C:/drivers/browser/ie.exe
#chrome.binary = /usr/bin/google-chrome
#webdriver.chrome.driver = /iplanrio/java/utilitarios/selenium/webdriver/chromedriver
#webdriver.chrome.driver = C:/drivers/browser/chrome/91/chromedriver.exe		
webdriver.chrome.driver = D:/workspace/prefrio/PrefRioTest/drivers/142/chromedriver.exe
webdriver.ff.driver = C:/Users/brboe/eclipse-workspace/UdemyTest/drivers/geckodriver.exe
selenium.headless = não
